package app.shosetsu.android.domain.model.database

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.ForeignKey
import androidx.room.Index
import androidx.room.PrimaryKey
import app.shosetsu.android.common.enums.ReadingStatus
import app.shosetsu.android.domain.model.local.ChapterEntity
import app.shosetsu.android.dto.Convertible
import app.shosetsu.lib.Novel.Chapter

/*
 * This file is part of Shosetsu.
 *
 * Shosetsu is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Shosetsu is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Shosetsu.  If not, see <https://www.gnu.org/licenses/>.
 */

/**
 * shosetsu
 * @since 05 / 12 / 2020
 *
 * @param id autogenerated id of this chapter
 * @param url [Chapter.link]
 * @param novelID [DBNovelEntity.id]
 * @param extensionID id of extension this chapter requires. Not linked to allow for extension swap.
 * @param title [Chapter.title]
 * @param releaseDate [Chapter.release]
 * @param order [Chapter.order]
 * @param readingPosition Percentage of the way through a chapter
 * @param readingStatus Status of reading this chapter
 * @param bookmarked Is this chapter bookmarked or not
 * @param isSaved Is this chapter downloaded or not
 */
@Entity(
	tableName = "chapters",
	foreignKeys = [
		ForeignKey(
			entity = DBNovelEntity::class,
			parentColumns = ["id"],
			childColumns = ["novelID"],
			onDelete = ForeignKey.CASCADE
		)
	],
	indices = [
		Index("novelID"),
		Index(value = ["url", "formatterID"], unique = true),
	]
)
data class DBChapterEntity(
	@PrimaryKey(autoGenerate = true)
	var id: Int? = null,

	var url: String,

	val novelID: Int,

	@ColumnInfo(name = "formatterID")
	val extensionID: Int,

	var title: String,

	var releaseDate: String,

	var order: Double,

	var readingPosition: Double = 0.0,

	var readingStatus: ReadingStatus = ReadingStatus.UNREAD,

	var bookmarked: Boolean = false,

	var isSaved: Boolean = false,
) : Convertible<ChapterEntity> {
	override fun convertTo(): ChapterEntity = ChapterEntity(
		id,
		url,
		novelID,
		extensionID,
		title,
		releaseDate,
		order,
		readingPosition,
		readingStatus,
		bookmarked,
		isSaved
	)
}
